openapi: 3.0.0
info:
  title: TalkNeT API
  version: 1.0.0
  description: TalkNeTのAPI
servers:
  - url: https://nandeyanen.ie-t.net/talkit/api/v1/TalkNeT
    description: （使用できません）Version 1

paths:
  /posts:
    post:
      summary: newPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '201':
          description: Post success
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: string
        '401':
          description: Auth failed
      security:
        - sessionId: []
    get:
      summary: GetPostIndex
      parameters:
        - name: type
          in: query
          required: false
          schema:
            type: string
            enum: [latest, random]
            default: latest
        - name: count
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
      responses:
        '200':
          description: Get Post index success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    postId:
                      type: string
                    content:
                      type: string
                    author:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    likes:
                      type: integer

  /posts/{postId}:
    get:
      summary: GetPost
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get success
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: string
                  content:
                    type: string
                  author:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '404':
          description: No posts exist

    patch:
      summary: EditPost
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Edit success
        '401':
          description: Auth failed
        '403':
          description: No permission
        '404':
          description: No posts exist
      security:
        - sessionId: []

    delete:
      summary: DelPost
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Del success
        '401':
          description: Auth Failed
        '403':
          description: No permission
      security:
        - sessionId: []

  /posts/{postId}/comments:
    post:
      summary: NewComment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
              required:
                - comment
      responses: 
        '201':
          description: Comment Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  commentId:
                    type: string
        '401':
          description: Auth Failed
        '404':
          description: No posts exist
      security:
        - sessionId: []

    get:
      summary: GetComments
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get comments success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    commentId:
                      type: string
                    comment:
                      type: string
                    author:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
        '404':
          description: No posts exist

    patch:
      summary: EditComment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
              required:
                - comment
      responses:
        '200':
          description: Edit success
        '401':
          description: Auth failed
        '403':
          description: No permission
        '404':
          description: No comments exist
      security:
        - sessionId: []

  /posts/{postId}/love:
    post:
      summary: AddLike
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                favorite:
                  type: boolean
              required:
                - favorite
      responses:
        '200':
          description: Like Success
        '401':
          description: Auth Failed
        '404':
          description: No posts exist
      security:
        - sessionId: []

components:
  securitySchemes:
    sessionId:
      type: apiKey
      in: header
      name: X-Session-Id

