openapi: 3.0.0
info:
  title: Talker Common API
  version: 1.0.0
  description: TalkerのAPI
servers:
  - url: https://nandeyanen.ie-t.net/talkit/api/v1/Talker
    description: （使用できません）Version 1

paths:
  /messages:
    get:
      summary: GetMessages
      parameters:
        - name: count
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        sender:
                          type: string
                        recipient:
                          type: string
                        content:
                          type: string
                        title:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
        '401':
          description: Auth failed
      security:
        - sessionId: []

  /send:
    post:
      summary: SendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient:
                  type: string
                title:
                  type: string
                content:
                  type: string
              required:
                - recipient
                - title
                - content
      responses:
        '200':
          description: Send success
        '401':
          description: Auth failed
        '404':
          description: User is Not Found
      security:
        - sessionId: []

  /user_messages:
    get:
      summary: GetUserMessages
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        sender:
                          type: string
                        recipient:
                          type: string
                        content:
                          type: string
                        title:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
        '401':
          description: Auth failed
        '404':
          description: User is Not Found
      security:
        - sessionId: []

components:
  securitySchemes:
    sessionId:
      type: apiKey
      in: header
      name: X-Session-Id
