openapi: 3.0.0
info:
  title: Talker Common API
  version: 1.0.0
  description: TalkerのAPI
servers:
  - url: https://nandeyanen.ie-t.net/talkit/api/v1/Talker
    description: （使用できません）Version 1

paths:
  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
        '401':
          description: Auth failed

  /logout:
    post:
      summary: Logout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
              required:
                - sessionId
      responses:
        '200':
          description: Logout Success
        '401':
          description: Auth failed
      security:
        - sessionId: []

  /notifications:
    get:
      summary: GetNotifications
      responses:
        '200':
          description: Notice get success
          content:
            application/json:
              schema:
                type: object
                properties:
                  notices:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        postUrl:
                          type: string
                        user:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
        '401':
          description: Auth failed
      security:
        - sessionId: []

components:
  securitySchemes:
    sessionId:
      type: apiKey
      in: header
      name: X-Session-Id
