openapi: 3.0.0
info:
  title: Talkit API
  version: 1.0.0
  description: Talkit全般のAPI
servers:
  - url: https://nandeyanen.ie-t.net/talkit/api/v1
    description: （使用できません）Version 1

paths:
  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
        '401':
          description: Auth failed

  /logout:
    post:
      summary: Logout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
              required:
                - sessionId
      responses:
        '200':
          description: Logout Success
        '401':
          description: Auth failed
  
  /get_notice:
    get:
      summary: getNoitce
      parameters:
        - in: query
          name: sessionId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notice get success
          content:
            application/json:
              schema:
                type: object
                properties:
                  notices:
                    type: array
                    items:
                      type: string
        '401':
          description: Auth failed
